/* SPDX-License-Identifier: LGPL-2.1-or-later */
/*
 * Copyright 2024-2026 NXP
 *
 * Conversion between the uGuzzi structures and the NXP NEOISP UAPI
 */

#pragma once

#include <stdint.h>

#include <linux/nxp_neoisp.h>
#include "params.h"

extern "C" {
#include "uguzzi/uguzzi_isp_out.h"
}

/*
 * Check the ISP defines are matching between the ones from UAPI and
 * the ones used by the uguzzi libraries.
 */
#if !(NEO_AF_REG_STATS_ROIS_CNT == AUTOFOCUS_ROI_CNT)
#error "mismatch NEO_AF_REG_STATS_ROIS_CNT with AUTOFOCUS_ROI_CNT"
#endif
#if !(NEO_CTEMP_COLOR_ROIS_CNT == CTEMP_COLOR_ROIS_CNT)
#error "mismatch NEO_CTEMP_COLOR_ROIS_CNT with CTEMP_COLOR_ROIS_CNT"
#endif
#if !(NEO_CTEMP_CSC_MATRIX_SIZE == CTEMP_CSC_MATRIX_SIZE)
#error "mismatch NEO_CTEMP_CSC_MATRIX_SIZE with CTEMP_CSC_MATRIX_SIZE"
#endif
#if !(NEO_CTEMP_CSC_OFFSET_VECTOR_SIZE == CTEMP_CSC_OFFSET_VECTOR_SIZE)
#error "mismatch NEO_CTEMP_CSC_OFFSET_VECTOR_SIZE with CTEMP_CSC_OFFSET_VECTOR_SIZE"
#endif
#if !(NEO_GAMMA_MATRIX_SIZE == GCM_INPUT_CSC_MATRIX_ROWS)
#error "mismatch NEO_GAMMA_MATRIX_SIZE with GCM_INPUT_CSC_MATRIX_ROWS"
#endif
#if !(NEO_GAMMA_MATRIX_SIZE == GCM_INPUT_CSC_MATRIX_COLS)
#error "mismatch NEO_GAMMA_MATRIX_SIZE with GCM_INPUT_CSC_MATRIX_COLS"
#endif
#if !(NEO_GAMMA_OFFSETS_SIZE == GCM_INPUT_CSC_OFFSETS_SIZE)
#error "mismatch NEO_GAMMA_OFFSETS_SIZE with GCM_INPUT_CSC_OFFSETS_SIZE"
#endif
#if !(NEO_GAMMA_MATRIX_SIZE == GCM_OUTPUT_CSC_MATRIX_ROWS)
#error "mismatch NEO_GAMMA_MATRIX_SIZE with GCM_OUTPUT_CSC_MATRIX_ROWS"
#endif
#if !(NEO_GAMMA_MATRIX_SIZE == GCM_OUTPUT_CSC_MATRIX_COLS)
#error "mismatch NEO_GAMMA_MATRIX_SIZE with GCM_OUTPUT_CSC_MATRIX_COLS"
#endif
#if !(NEO_GAMMA_OFFSETS_SIZE == GCM_OUTPUT_CSC_OFFSETS_SIZE)
#error "mismatch NEO_GAMMA_OFFSETS_SIZE with GCM_OUTPUT_CSC_OFFSETS_SIZE"
#endif
#if !(NEO_AF_FILTERS_CNT == AUTOFOCUS_FIL_COEFFS_CNT)
#error "mismatch NEO_AF_FILTERS_CNT with AUTOFOCUS_FIL_COEFFS_CNT"
#endif
#if !(NEO_AF_ROIS_CNT == AUTOFOCUS_ROI_CNT)
#error "mismatch NEO_AF_ROIS_CNT with AUTOFOCUS_ROI_CNT"
#endif
#if !(NEO_STAT_HIST_CNT == STAT_HIST_CNT)
#error "mismatch NEO_STAT_HIST_CNT with STAT_HIST_CNT"
#endif
#if !(NEO_RGBIR_STAT_HIST_CNT == RGBIR_STAT_HIST_CNT)
#error "mismatch NEO_RGBIR_STAT_HIST_CNT with RGBIR_STAT_HIST_CNT"
#endif
#if !(NEO_DRC_GLOBAL_TONEMAP_SIZE == DRC_GLOBAL_TONEMAP_SIZE)
#error "mismatch NEO_DRC_GLOBAL_TONEMAP_SIZE with DRC_GLOBAL_TONEMAP_SIZE"
#endif
#if !(NEO_DRC_LOCAL_TONEMAP_SIZE == DRC_LOCAL_TONEMAP_SIZE)
#error "mismatch NEO_DRC_LOCAL_TONEMAP_SIZE with DRC_LOCAL_TONEMAP_SIZE"
#endif
#if !(NEO_RGB2YUV_MATRIX_SIZE == RGB2YUV_MATRIX_SIZE)
#error "mismatch NEO_RGB2YUV_MATRIX_SIZE with RGB2YUV_MATRIX_SIZE"
#endif
#if !(RGB2YUV_MATRIX_SIZE == CCM_MATRIX_SIZE)
#error "mismatch RGB2YUV_MATRIX_SIZE with CCM_MATRIX_SIZE"
#endif
#if !(NEO_VIGNETTING_TABLE_SIZE == VIGNETTING_TABLE_SIZE)
#error "mismatch NEO_VIGNETTING_TABLE_SIZE with VIGNETTING_TABLE_SIZE"
#endif
#if !(NEO_CTEMP_REG_STATS_CROIS_CNT == CTEMP_COLOR_ROIS_CNT)
#error "mismatch NEO_CTEMP_REG_STATS_CROIS_CNT with CTEMP_COLOR_ROIS_CNT"
#endif
#if !(NEO_CTEMP_R_SUM_CNT == (IMX9X_ISP_MAX_GRID_HORIZONTAL * IMX9X_ISP_MAX_GRID_VERTICAL))
#error "mismatch NEO_CTEMP_R_SUM_CNT with (IMX9X_ISP_MAX_GRID_HORIZONTAL * IMX9X_ISP_MAX_GRID_VERTICAL)"
#endif
#if !(NEO_CTEMP_G_SUM_CNT == (IMX9X_ISP_MAX_GRID_HORIZONTAL * IMX9X_ISP_MAX_GRID_VERTICAL))
#error "mismatch NEO_CTEMP_G_SUM_CNT with (IMX9X_ISP_MAX_GRID_HORIZONTAL * IMX9X_ISP_MAX_GRID_VERTICAL)"
#endif
#if !(NEO_CTEMP_B_SUM_CNT == (IMX9X_ISP_MAX_GRID_HORIZONTAL * IMX9X_ISP_MAX_GRID_VERTICAL))
#error "mismatch NEO_CTEMP_B_SUM_CNT with (IMX9X_ISP_MAX_GRID_HORIZONTAL * IMX9X_ISP_MAX_GRID_VERTICAL)"
#endif
#if !(NEO_CTEMP_PIX_CNT_CNT == (IMX9X_ISP_MAX_GRID_HORIZONTAL * IMX9X_ISP_MAX_GRID_VERTICAL))
#error "mismatch NEO_CTEMP_PIX_CNT_CNT with (IMX9X_ISP_MAX_GRID_HORIZONTAL * IMX9X_ISP_MAX_GRID_VERTICAL)"
#endif
#if !(NEO_DRC_GLOBAL_HIST_ROI_CNT == DRC_GLOBAL_TONEMAP_SIZE)
#error "mismatch NEO_DRC_GLOBAL_HIST_ROI_CNT with DRC_GLOBAL_TONEMAP_SIZE"
#endif
#if !(NEO_DRC_LOCAL_SUM_CNT == DRC_LOCAL_TONEMAP_SIZE)
#error "mismatch NEO_DRC_LOCAL_SUM_CNT with DRC_LOCAL_TONEMAP_SIZE"
#endif

namespace libcamera::ipa::nxpneo {

void convertUguzziIspCfg2IspDrvCfg(imx9x_isp_cfg_prms_t *cfgParams,
				   uint32_t longest2ShortestFrameRatio,
				   NxpNeoParams *neoispMetaParams);
}
